### ISSUE TITLE
Turn vbc into abc files

### ISSUE THREAD

**Issue by GregorCH** [pierre-lebodic/bnb-mip-estimates#2]
Please commit also the abc files in addition to the vbc files to simplify testing. They should go into trees/abc, I guess.

Can you add a Readme file that lists the relevant data for the instances, e.g., how large the trees are, and how the performance of the estimations is? The readme file should be Markdown and go into trees/
It would be nice to summarize in there how the trees have been obtained exactly.

**Comment by JanMerlinV** [comment]
I now commited the large abc files as well as some smaller ones. For now the instance information is only about the larger instances, but I will extend that and commit a script for generating that information in the future.

If you want anything else in the README, let me know!
