### ISSUE TITLE
Use sum of weights as progress measure

### ISSUE THREAD

**Issue by GregorCH** [pierre-lebodic/bnb-mip-estimates#8]
Computing the weight of each node at the frontier (the weight that is used in sampling, which we can define using uniform or "ratio" probabilities). The sum of the weights of the nodes at the frontier is always 1 (if we include the leaves of the final tree), but the sum of weights of the open nodes gives us a measure of how much of the tree there still is to explore.

@JanMerlinV has already remarked some flaws of this technique:

> We can immediately see how this might lead to problems: Imagine an arbitrarily large full binary tree. Now add such a chain of length ten above the root node, so that the full tree sits at depth 10 instead of depth 1. Assuming a node selection like ours and selection percentages u_k=0.5, when reaching the root of the full subtree we have already sampled all the leaves above it. Since they are of so low depth, not only are their estimates low, but the weight of their estimates is high. Before even sampling a single leaf of the arbitrarily large subtree, the weight of our estimations has already reached 1-(1/2)^10 >= 0.999. The rest of the leaves will now linearly increase the total estimation until we reach the tree size.

@pierre-lebodic :
> The absurdity of this technique can be seen in the case where you have one leaf at depth 1. It has weight 0.5, and it says it's half of your leaves. Even after finding M other leaves, this leaf still has the same weight...

**Comment by GregorCH** [comment]
I think that this progress measure is readily available by using 1 - (sum weights seen so far). @JanMerlinV , can you verify this and report back?

**Comment by JanMerlinV** [comment]
Yes, this is currently done during the calculation of the standard deviations in `sampletree.calculateStds()`, where I add up the `sample.totalPhi()` for each sample.
